### ISSUE TITLE
[1.3.0.5] Game temporarily freezes on startup

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#37]
On 1.3.0.5, game freezes after the task sound effect until an error related to "checking visits" on a website shows up. Here is the log output:

this doesn't always happen every time though

```
[Info   : YuEzTools] [00:17:38][Translator]the id is English
[Message: YuEzTools] [00:17:38][Updater]Using https://raw.githubusercontent.com/Team-YuTeam/YuEzTools/main/YuEzTools/info.json
[Message: YuEzTools] [00:17:38][CheckRelease]https://raw.githubusercontent.com/Team-YuTeam/YuEzTools/main/YuEzTools/info.json
[Message: YuEzTools] [00:17:38][CheckRelease]Check For Update: True
[Info   : YuEzTools] [00:17:38][CheckRelease]Has Update: False
[Info   : YuEzTools] [00:17:38][CheckRelease]Latest Version: 1.3.0.5
[Info   : YuEzTools] [00:17:38][CheckRelease]Minimum Version: 1.3.0.5
[Info   : YuEzTools] [00:17:38][CheckRelease]Creation: 1
[Info   : YuEzTools] [00:17:38][CheckRelease]Force Update: False
[Info   : YuEzTools] [00:17:38][CheckRelease]Github Url: https://github.com/Team-YuTeam/YuEzTools/releases/latest/download/YuEzTools.dll
[Info   : YuEzTools] [00:17:38][CheckRelease]Gitee Url: https://gitee.com/xigua_ya/YuEzTools/releases/download/v1.3.0.5/YuEzTools.dll
[Info   : YuEzTools] [00:17:38][CheckRelease]kkGithub Url: https://kkgithub.com/Team-YuTeam/YuEzTools/releases/latest/download/YuEzTools.dll
[Info   : YuEzTools] [00:17:38][CheckRelease]Announcement (English): Welcome to use YuEzTools!\nYuET is best\nSponsor Yu Please click the first two buttons
[Info   : YuEzTools] [00:17:38][CheckRelease]Announcement (SChinese): 欢迎使用YuEzTools!\n全新YuEzTools！\n功能增多，质量提升！\n赞助Yu请点击前两个按钮
[Info   : YuEzTools] [00:17:38][CheckRelease]File MD5: 543ff1ed93825cbe18a1a1d724b0f8d8
[Info   : YuEzTools] [00:17:38][CheckRelease]543ff1ed93825cbe18a1a1d724b0f8d8
[Info   : YuEzTools] [00:17:38][CheckNowFileMD5]MD5 TRUE
[Info   : YuEzTools] [00:17:38][Translator]the id is English
[Info   : YuEzTools] [00:17:38][ver]1.3.0.5
[Info   : YuEzTools] [00:17:38][ver]1.3.0.5
[Info   : YuEzTools] [00:17:38][ver]1.3.0.5
[Info   : YuEzTools] [00:17:38][ver]1.3.0.5
[Message: YuEzTools] [00:17:38][AddVisit]开始从2018k检查visit
[Error  : YuEzTools] [00:19:18][AddVisit]增加Visit时发生错误，已忽略
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YuEzTools.Updater.ModUpdater.Get(String url) in D:\zhuomian\code\YuEzTools\YuEzTools\Modules\Updater.cs:line 228
   at YuEzTools.Updater.ModUpdater.AddVisit() in D:\zhuomian\code\YuEzTools\YuEzTools\Modules\Updater.cs:line 93
   at YuEzTools.Updater.ModUpdater.StartPostfix() in D:\zhuomian\code\YuEzTools\YuEzTools\Modules\Updater.cs:line 79
   at DMD<MainMenuManager::Start>(MainMenuManager this)
   at (il2cpp -> managed) Start(IntPtr , Il2CppMethodInfo* )
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YuEzTools.Updater.ModUpdater.Get(String url) in D:\zhuomian\code\YuEzTools\YuEzTools\Modules\Updater.cs:line 228
   at YuEzTools.Updater.ModUpdater.AddVisit() in D:\zhuomian\code\YuEzTools\YuEzTools\Modules\Updater.cs:line 93
[Info   : YuEzTools] "Override Disconnect Text" is created
[Info   : YuEzTools] [00:19:18][DisconnectPatch]An unknown error disconnected you from the server.
[Info   : YuEzTools] [00:19:18][DisconnectPatch]An unknown error disconnected you from the server.
[Info   : YuEzTools] "Override Disconnect Text" is finished
[Info   : YuEzTools] "Set Online Status" is created
[Info   : YuEzTools] "Set Online Status" is finished
```

**Comment by Night-GUA** [comment]
because the website is in china, I will change it on next version
